/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for Jerboa
*/

/*
    Board identifier
*/
#define BOARD_JERBOA
#define BOARD_NAME                     "Jerboa"

/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   0U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32L051xx

/*
    Other settings.
*/
#define STM32_HSE_BYPASS               
#define STM32_LSEDRV                   (3U << 11U)

/*
    IO pins assignments.
*/
#define GPIOA_PIN0                     0U
#define GPIOA_FREQ_CTRL                1U
#define GPIOA_RADIO_SDN                2U
#define GPIOA_RADIO_NIRQ               3U
#define GPIOA_RADIO_NSS                4U
#define GPIOA_MCU_SCK                  5U
#define GPIOA_MCU_MISO                 6U
#define GPIOA_MCU_MOSI                 7U
#define GPIOA_GPS_EXTINT               8U
#define GPIOA_GPS_TX                   9U
#define GPIOA_GPS_RX                   10U
#define GPIOA_GPS_NRST                 11U
#define GPIOA_PIN12                    12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_LED                      15U

#define GPIOB_BATT_V                   0U
#define GPIOB_SOLAR_CELL_V             1U
#define GPIOB_RADIO_PWR_EN             2U
#define GPIOB_PIN3                     3U
#define GPIOB_PIN4                     4U
#define GPIOB_WSPR_EN                  5U
#define GPIOB_I2C_SCL                  6U
#define GPIOB_I2C_SDA                  7U
#define GPIOB_PIN8                     8U
#define GPIOB_PIN9                     9U
#define GPIOB_PIN10                    10U
#define GPIOB_PIN11                    11U
#define GPIOB_PIN12                    12U
#define GPIOB_PIN13                    13U
#define GPIOB_PIN14                    14U
#define GPIOB_PIN15                    15U

#define GPIOC_PIN0                     0U
#define GPIOC_PIN1                     1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_PIN4                     4U
#define GPIOC_PIN5                     5U
#define GPIOC_PIN6                     6U
#define GPIOC_PIN7                     7U
#define GPIOC_PIN8                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_PIN10                    10U
#define GPIOC_PIN11                    11U
#define GPIOC_PIN12                    12U
#define GPIOC_PIN13                    13U
#define GPIOC_PIN14                    14U
#define GPIOC_PIN15                    15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_PIN8                     8U
#define GPIOD_PIN9                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_PIN11                    11U
#define GPIOD_PIN12                    12U
#define GPIOD_PIN13                    13U
#define GPIOD_PIN14                    14U
#define GPIOD_PIN15                    15U

#define GPIOH_PIN0                     0U
#define GPIOH_PIN1                     1U
#define GPIOH_PIN2                     2U
#define GPIOH_PIN3                     3U
#define GPIOH_PIN4                     4U
#define GPIOH_PIN5                     5U
#define GPIOH_PIN6                     6U
#define GPIOH_PIN7                     7U
#define GPIOH_PIN8                     8U
#define GPIOH_PIN9                     9U
#define GPIOH_PIN10                    10U
#define GPIOH_PIN11                    11U
#define GPIOH_PIN12                    12U
#define GPIOH_PIN13                    13U
#define GPIOH_PIN14                    14U
#define GPIOH_PIN15                    15U

/*
    IO lines assignments.
*/
#define LINE_BATT_V                    PAL_LINE(GPIOB, 0U)
#define LINE_FREQ_CTRL                 PAL_LINE(GPIOA, 1U)
#define LINE_GPS_EXTINT                PAL_LINE(GPIOA, 8U)
#define LINE_GPS_NRST                  PAL_LINE(GPIOA, 11U)
#define LINE_GPS_RX                    PAL_LINE(GPIOA, 10U)
#define LINE_GPS_TX                    PAL_LINE(GPIOA, 9U)
#define LINE_I2C_SCL                   PAL_LINE(GPIOB, 6U)
#define LINE_I2C_SDA                   PAL_LINE(GPIOB, 7U)
#define LINE_LED                       PAL_LINE(GPIOA, 15U)
#define LINE_MCU_MISO                  PAL_LINE(GPIOA, 6U)
#define LINE_MCU_MOSI                  PAL_LINE(GPIOA, 7U)
#define LINE_MCU_SCK                   PAL_LINE(GPIOA, 5U)
#define LINE_RADIO_NIRQ                PAL_LINE(GPIOA, 3U)
#define LINE_RADIO_NSS                 PAL_LINE(GPIOA, 4U)
#define LINE_RADIO_PWR_EN              PAL_LINE(GPIOB, 2U)
#define LINE_RADIO_SDN                 PAL_LINE(GPIOA, 2U)
#define LINE_SOLAR_CELL_V              PAL_LINE(GPIOB, 1U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_WSPR_EN                   PAL_LINE(GPIOB, 5U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - PIN0                         (unused).
 * PA1  - FREQ_CTRL                    (output pushpull starthigh pullup).
 * PA2  - RADIO_SDN                    (output pushpull floating).
 * PA3  - RADIO_NIRQ                   (output pushpull starthigh pullup).
 * PA4  - RADIO_NSS                    (output pushpull starthigh pullup highspeed).
 * PA5  - MCU_SCK                      (af0 pushpull starthigh pullup highspeed).
 * PA6  - MCU_MISO                     (af0 pushpull starthigh pullup highspeed).
 * PA7  - MCU_MOSI                     (af0 pushpull starthigh pullup highspeed).
 * PA8  - GPS_EXTINT                   (output pushpull startlow pulldown).
 * PA9  - GPS_TX                       (af4 pushpull starthigh pullup highspeed).
 * PA10 - GPS_RX                       (af4 pushpull starthigh pullup highspeed).
 * PA11 - GPS_NRST                     (output pushpull starthigh pullup).
 * PA12 - PIN12                        (unused).
 * PA13 - SWDIO                        (af0 pushpull starthigh pullup highspeed).
 * PA14 - SWCLK                        (af0 pushpull starthigh pulldown highspeed).
 * PA15 - LED                          (output pushpull).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_INPUT(GPIOA_PIN0) | \
                                        PIN_MODE_OUTPUT(GPIOA_FREQ_CTRL) | \
                                        PIN_MODE_OUTPUT(GPIOA_RADIO_SDN) | \
                                        PIN_MODE_OUTPUT(GPIOA_RADIO_NIRQ) | \
                                        PIN_MODE_OUTPUT(GPIOA_RADIO_NSS) | \
                                        PIN_MODE_ALTERNATE(GPIOA_MCU_SCK) | \
                                        PIN_MODE_ALTERNATE(GPIOA_MCU_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_MCU_MOSI) | \
                                        PIN_MODE_OUTPUT(GPIOA_GPS_EXTINT) | \
                                        PIN_MODE_ALTERNATE(GPIOA_GPS_TX) | \
                                        PIN_MODE_ALTERNATE(GPIOA_GPS_RX) | \
                                        PIN_MODE_OUTPUT(GPIOA_GPS_NRST) | \
                                        PIN_MODE_INPUT(GPIOA_PIN12) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_LED))

#define VAL_GPIOA_OTYPER               (PIN_OTYPE_OPENDRAIN(GPIOA_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_FREQ_CTRL) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RADIO_SDN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RADIO_NIRQ) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RADIO_NSS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_MCU_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_MCU_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_MCU_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_EXTINT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_TX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_GPS_NRST) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOA_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_LED))

#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_LOW(GPIOA_PIN0) | \
                                        PIN_OSPEED_LOW(GPIOA_FREQ_CTRL) | \
                                        PIN_OSPEED_LOW(GPIOA_RADIO_SDN) | \
                                        PIN_OSPEED_LOW(GPIOA_RADIO_NIRQ) | \
                                        PIN_OSPEED_HIGH(GPIOA_RADIO_NSS) | \
                                        PIN_OSPEED_HIGH(GPIOA_MCU_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOA_MCU_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOA_MCU_MOSI) | \
                                        PIN_OSPEED_LOW(GPIOA_GPS_EXTINT) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_TX) | \
                                        PIN_OSPEED_HIGH(GPIOA_GPS_RX) | \
                                        PIN_OSPEED_LOW(GPIOA_GPS_NRST) | \
                                        PIN_OSPEED_LOW(GPIOA_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_LOW(GPIOA_LED))

#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLDOWN(GPIOA_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOA_FREQ_CTRL) | \
                                        PIN_PUPD_FLOATING(GPIOA_RADIO_SDN) | \
                                        PIN_PUPD_PULLUP(GPIOA_RADIO_NIRQ) | \
                                        PIN_PUPD_PULLUP(GPIOA_RADIO_NSS) | \
                                        PIN_PUPD_PULLUP(GPIOA_MCU_SCK) | \
                                        PIN_PUPD_PULLUP(GPIOA_MCU_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOA_MCU_MOSI) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_GPS_EXTINT) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_TX) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_GPS_NRST) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOA_SWDIO) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWCLK) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_LED))

#define VAL_GPIOA_ODR                  (PIN_OD_LOW(GPIOA_PIN0) | \
                                        PIN_OD_HIGH(GPIOA_FREQ_CTRL) | \
                                        PIN_OD_LOW(GPIOA_RADIO_SDN) | \
                                        PIN_OD_HIGH(GPIOA_RADIO_NIRQ) | \
                                        PIN_OD_HIGH(GPIOA_RADIO_NSS) | \
                                        PIN_OD_HIGH(GPIOA_MCU_SCK) | \
                                        PIN_OD_HIGH(GPIOA_MCU_MISO) | \
                                        PIN_OD_HIGH(GPIOA_MCU_MOSI) | \
                                        PIN_OD_LOW(GPIOA_GPS_EXTINT) | \
                                        PIN_OD_HIGH(GPIOA_GPS_TX) | \
                                        PIN_OD_HIGH(GPIOA_GPS_RX) | \
                                        PIN_OD_HIGH(GPIOA_GPS_NRST) | \
                                        PIN_OD_LOW(GPIOA_PIN12) | \
                                        PIN_OD_HIGH(GPIOA_SWDIO) | \
                                        PIN_OD_HIGH(GPIOA_SWCLK) | \
                                        PIN_OD_LOW(GPIOA_LED))

#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOA_FREQ_CTRL, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RADIO_SDN, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RADIO_NIRQ, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RADIO_NSS, 0U) | \
                                        PIN_AFIO_AF(GPIOA_MCU_SCK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_MCU_MISO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_MCU_MOSI, 0U))

#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_GPS_EXTINT, 0U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_TX, 4U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_RX, 4U) | \
                                        PIN_AFIO_AF(GPIOA_GPS_NRST, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_LED, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - BATT_V                       (analog floating).
 * PB1  - SOLAR_CELL_V                 (analog floating).
 * PB2  - RADIO_PWR_EN                 (output pushpull startlow pulldown).
 * PB3  - PIN3                         (unused).
 * PB4  - PIN4                         (unused).
 * PB5  - WSPR_EN                      (output pushpull startlow pulldown).
 * PB6  - I2C_SCL                      (af1 opendrain starthigh floating highspeed).
 * PB7  - I2C_SDA                      (af1 opendrain starthigh floating highspeed).
 * PB8  - PIN8                         (unused).
 * PB9  - PIN9                         (unused).
 * PB10 - PIN10                        (unused).
 * PB11 - PIN11                        (unused).
 * PB12 - PIN12                        (unused).
 * PB13 - PIN13                        (unused).
 * PB14 - PIN14                        (unused).
 * PB15 - PIN15                        (unused).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_ANALOG(GPIOB_BATT_V) | \
                                        PIN_MODE_ANALOG(GPIOB_SOLAR_CELL_V) | \
                                        PIN_MODE_OUTPUT(GPIOB_RADIO_PWR_EN) | \
                                        PIN_MODE_INPUT(GPIOB_PIN3) | \
                                        PIN_MODE_INPUT(GPIOB_PIN4) | \
                                        PIN_MODE_OUTPUT(GPIOB_WSPR_EN) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SCL) | \
                                        PIN_MODE_ALTERNATE(GPIOB_I2C_SDA) | \
                                        PIN_MODE_INPUT(GPIOB_PIN8) | \
                                        PIN_MODE_INPUT(GPIOB_PIN9) | \
                                        PIN_MODE_INPUT(GPIOB_PIN10) | \
                                        PIN_MODE_INPUT(GPIOB_PIN11) | \
                                        PIN_MODE_INPUT(GPIOB_PIN12) | \
                                        PIN_MODE_INPUT(GPIOB_PIN13) | \
                                        PIN_MODE_INPUT(GPIOB_PIN14) | \
                                        PIN_MODE_INPUT(GPIOB_PIN15))

#define VAL_GPIOB_OTYPER               (PIN_OTYPE_OPENDRAIN(GPIOB_BATT_V) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_SOLAR_CELL_V) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RADIO_PWR_EN) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN3) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_WSPR_EN) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_I2C_SCL) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_I2C_SDA) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN8) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN9) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN10) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN11) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN12) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN13) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN14) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOB_PIN15))

#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_LOW(GPIOB_BATT_V) | \
                                        PIN_OSPEED_LOW(GPIOB_SOLAR_CELL_V) | \
                                        PIN_OSPEED_LOW(GPIOB_RADIO_PWR_EN) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN3) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN4) | \
                                        PIN_OSPEED_LOW(GPIOB_WSPR_EN) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SCL) | \
                                        PIN_OSPEED_HIGH(GPIOB_I2C_SDA) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN8) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN9) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN10) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN11) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN12) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN13) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN14) | \
                                        PIN_OSPEED_LOW(GPIOB_PIN15))

#define VAL_GPIOB_PUPDR                (PIN_PUPD_FLOATING(GPIOB_BATT_V) | \
                                        PIN_PUPD_FLOATING(GPIOB_SOLAR_CELL_V) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_RADIO_PWR_EN) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN3) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN4) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_WSPR_EN) | \
                                        PIN_PUPD_FLOATING(GPIOB_I2C_SCL) | \
                                        PIN_PUPD_FLOATING(GPIOB_I2C_SDA) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN8) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN9) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN10) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN11) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN13) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN14) | \
                                        PIN_PUPD_PULLDOWN(GPIOB_PIN15))

#define VAL_GPIOB_ODR                  (PIN_OD_LOW(GPIOB_BATT_V) | \
                                        PIN_OD_LOW(GPIOB_SOLAR_CELL_V) | \
                                        PIN_OD_LOW(GPIOB_RADIO_PWR_EN) | \
                                        PIN_OD_LOW(GPIOB_PIN3) | \
                                        PIN_OD_LOW(GPIOB_PIN4) | \
                                        PIN_OD_LOW(GPIOB_WSPR_EN) | \
                                        PIN_OD_HIGH(GPIOB_I2C_SCL) | \
                                        PIN_OD_HIGH(GPIOB_I2C_SDA) | \
                                        PIN_OD_LOW(GPIOB_PIN8) | \
                                        PIN_OD_LOW(GPIOB_PIN9) | \
                                        PIN_OD_LOW(GPIOB_PIN10) | \
                                        PIN_OD_LOW(GPIOB_PIN11) | \
                                        PIN_OD_LOW(GPIOB_PIN12) | \
                                        PIN_OD_LOW(GPIOB_PIN13) | \
                                        PIN_OD_LOW(GPIOB_PIN14) | \
                                        PIN_OD_LOW(GPIOB_PIN15))

#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_BATT_V, 0U) | \
                                        PIN_AFIO_AF(GPIOB_SOLAR_CELL_V, 0U) | \
                                        PIN_AFIO_AF(GPIOB_RADIO_PWR_EN, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOB_WSPR_EN, 0U) | \
                                        PIN_AFIO_AF(GPIOB_I2C_SCL, 1U) | \
                                        PIN_AFIO_AF(GPIOB_I2C_SDA, 1U))

#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOB_PIN15, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - PIN1                         (unused).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - PIN4                         (unused).
 * PC5  - PIN5                         (unused).
 * PC6  - PIN6                         (unused).
 * PC7  - PIN7                         (unused).
 * PC8  - PIN8                         (unused).
 * PC9  - PIN9                         (unused).
 * PC10 - PIN10                        (unused).
 * PC11 - PIN11                        (unused).
 * PC12 - PIN12                        (unused).
 * PC13 - PIN13                        (unused).
 * PC14 - PIN14                        (unused).
 * PC15 - PIN15                        (unused).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_INPUT(GPIOC_PIN1) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_INPUT(GPIOC_PIN4) | \
                                        PIN_MODE_INPUT(GPIOC_PIN5) | \
                                        PIN_MODE_INPUT(GPIOC_PIN6) | \
                                        PIN_MODE_INPUT(GPIOC_PIN7) | \
                                        PIN_MODE_INPUT(GPIOC_PIN8) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_INPUT(GPIOC_PIN10) | \
                                        PIN_MODE_INPUT(GPIOC_PIN11) | \
                                        PIN_MODE_INPUT(GPIOC_PIN12) | \
                                        PIN_MODE_INPUT(GPIOC_PIN13) | \
                                        PIN_MODE_INPUT(GPIOC_PIN14) | \
                                        PIN_MODE_INPUT(GPIOC_PIN15))

#define VAL_GPIOC_OTYPER               (PIN_OTYPE_OPENDRAIN(GPIOC_PIN0) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN1) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN2) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN3) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN4) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN5) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN6) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN7) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN8) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN9) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN10) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN11) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN12) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN13) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN14) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOC_PIN15))

#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_LOW(GPIOC_PIN0) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN1) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN2) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN3) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN4) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN5) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN6) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN7) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN8) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN9) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN10) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN11) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN12) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN13) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN14) | \
                                        PIN_OSPEED_LOW(GPIOC_PIN15))

#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLDOWN(GPIOC_PIN0) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN1) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN4) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN5) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN6) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN7) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN8) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN9) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN10) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN11) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN13) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN14) | \
                                        PIN_PUPD_PULLDOWN(GPIOC_PIN15))

#define VAL_GPIOC_ODR                  (PIN_OD_LOW(GPIOC_PIN0) | \
                                        PIN_OD_LOW(GPIOC_PIN1) | \
                                        PIN_OD_LOW(GPIOC_PIN2) | \
                                        PIN_OD_LOW(GPIOC_PIN3) | \
                                        PIN_OD_LOW(GPIOC_PIN4) | \
                                        PIN_OD_LOW(GPIOC_PIN5) | \
                                        PIN_OD_LOW(GPIOC_PIN6) | \
                                        PIN_OD_LOW(GPIOC_PIN7) | \
                                        PIN_OD_LOW(GPIOC_PIN8) | \
                                        PIN_OD_LOW(GPIOC_PIN9) | \
                                        PIN_OD_LOW(GPIOC_PIN10) | \
                                        PIN_OD_LOW(GPIOC_PIN11) | \
                                        PIN_OD_LOW(GPIOC_PIN12) | \
                                        PIN_OD_LOW(GPIOC_PIN13) | \
                                        PIN_OD_LOW(GPIOC_PIN14) | \
                                        PIN_OD_LOW(GPIOC_PIN15))

#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN7, 0U))

#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN15, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - PIN8                         (unused).
 * PD9  - PIN9                         (unused).
 * PD10 - PIN10                        (unused).
 * PD11 - PIN11                        (unused).
 * PD12 - PIN12                        (unused).
 * PD13 - PIN13                        (unused).
 * PD14 - PIN14                        (unused).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_INPUT(GPIOD_PIN8) | \
                                        PIN_MODE_INPUT(GPIOD_PIN9) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_INPUT(GPIOD_PIN11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN12) | \
                                        PIN_MODE_INPUT(GPIOD_PIN13) | \
                                        PIN_MODE_INPUT(GPIOD_PIN14) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))

#define VAL_GPIOD_OTYPER               (PIN_OTYPE_OPENDRAIN(GPIOD_PIN0) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN1) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN2) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN3) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN4) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN5) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN6) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN7) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN8) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN9) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN10) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN11) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN12) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN13) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN14) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOD_PIN15))

#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_LOW(GPIOD_PIN0) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN1) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN2) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN3) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN4) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN5) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN6) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN7) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN8) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN9) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN10) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN11) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN12) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN13) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN14) | \
                                        PIN_OSPEED_LOW(GPIOD_PIN15))

#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLDOWN(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN8) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN9) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN11) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN13) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN14) | \
                                        PIN_PUPD_PULLDOWN(GPIOD_PIN15))

#define VAL_GPIOD_ODR                  (PIN_OD_LOW(GPIOD_PIN0) | \
                                        PIN_OD_LOW(GPIOD_PIN1) | \
                                        PIN_OD_LOW(GPIOD_PIN2) | \
                                        PIN_OD_LOW(GPIOD_PIN3) | \
                                        PIN_OD_LOW(GPIOD_PIN4) | \
                                        PIN_OD_LOW(GPIOD_PIN5) | \
                                        PIN_OD_LOW(GPIOD_PIN6) | \
                                        PIN_OD_LOW(GPIOD_PIN7) | \
                                        PIN_OD_LOW(GPIOD_PIN8) | \
                                        PIN_OD_LOW(GPIOD_PIN9) | \
                                        PIN_OD_LOW(GPIOD_PIN10) | \
                                        PIN_OD_LOW(GPIOD_PIN11) | \
                                        PIN_OD_LOW(GPIOD_PIN12) | \
                                        PIN_OD_LOW(GPIOD_PIN13) | \
                                        PIN_OD_LOW(GPIOD_PIN14) | \
                                        PIN_OD_LOW(GPIOD_PIN15))

#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))

#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOH setup:
 *
 * PH0  - PIN0                         (unused).
 * PH1  - PIN1                         (unused).
 * PH2  - PIN2                         (unused).
 * PH3  - PIN3                         (unused).
 * PH4  - PIN4                         (unused).
 * PH5  - PIN5                         (unused).
 * PH6  - PIN6                         (unused).
 * PH7  - PIN7                         (unused).
 * PH8  - PIN8                         (unused).
 * PH9  - PIN9                         (unused).
 * PH10 - PIN10                        (unused).
 * PH11 - PIN11                        (unused).
 * PH12 - PIN12                        (unused).
 * PH13 - PIN13                        (unused).
 * PH14 - PIN14                        (unused).
 * PH15 - PIN15                        (unused).
*/
#define VAL_GPIOH_MODER                (PIN_MODE_INPUT(GPIOH_PIN0) | \
                                        PIN_MODE_INPUT(GPIOH_PIN1) | \
                                        PIN_MODE_INPUT(GPIOH_PIN2) | \
                                        PIN_MODE_INPUT(GPIOH_PIN3) | \
                                        PIN_MODE_INPUT(GPIOH_PIN4) | \
                                        PIN_MODE_INPUT(GPIOH_PIN5) | \
                                        PIN_MODE_INPUT(GPIOH_PIN6) | \
                                        PIN_MODE_INPUT(GPIOH_PIN7) | \
                                        PIN_MODE_INPUT(GPIOH_PIN8) | \
                                        PIN_MODE_INPUT(GPIOH_PIN9) | \
                                        PIN_MODE_INPUT(GPIOH_PIN10) | \
                                        PIN_MODE_INPUT(GPIOH_PIN11) | \
                                        PIN_MODE_INPUT(GPIOH_PIN12) | \
                                        PIN_MODE_INPUT(GPIOH_PIN13) | \
                                        PIN_MODE_INPUT(GPIOH_PIN14) | \
                                        PIN_MODE_INPUT(GPIOH_PIN15))

#define VAL_GPIOH_OTYPER               (PIN_OTYPE_OPENDRAIN(GPIOH_PIN0) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN1) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN2) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN3) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN4) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN5) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN6) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN7) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN8) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN9) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN10) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN11) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN12) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN13) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN14) | \
                                        PIN_OTYPE_OPENDRAIN(GPIOH_PIN15))

#define VAL_GPIOH_OSPEEDR              (PIN_OSPEED_LOW(GPIOH_PIN0) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN1) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN2) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN3) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN4) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN5) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN6) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN7) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN8) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN9) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN10) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN11) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN12) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN13) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN14) | \
                                        PIN_OSPEED_LOW(GPIOH_PIN15))

#define VAL_GPIOH_PUPDR                (PIN_PUPD_PULLDOWN(GPIOH_PIN0) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN1) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN2) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN3) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN4) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN5) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN6) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN7) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN8) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN9) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN10) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN11) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN13) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN14) | \
                                        PIN_PUPD_PULLDOWN(GPIOH_PIN15))

#define VAL_GPIOH_ODR                  (PIN_OD_LOW(GPIOH_PIN0) | \
                                        PIN_OD_LOW(GPIOH_PIN1) | \
                                        PIN_OD_LOW(GPIOH_PIN2) | \
                                        PIN_OD_LOW(GPIOH_PIN3) | \
                                        PIN_OD_LOW(GPIOH_PIN4) | \
                                        PIN_OD_LOW(GPIOH_PIN5) | \
                                        PIN_OD_LOW(GPIOH_PIN6) | \
                                        PIN_OD_LOW(GPIOH_PIN7) | \
                                        PIN_OD_LOW(GPIOH_PIN8) | \
                                        PIN_OD_LOW(GPIOH_PIN9) | \
                                        PIN_OD_LOW(GPIOH_PIN10) | \
                                        PIN_OD_LOW(GPIOH_PIN11) | \
                                        PIN_OD_LOW(GPIOH_PIN12) | \
                                        PIN_OD_LOW(GPIOH_PIN13) | \
                                        PIN_OD_LOW(GPIOH_PIN14) | \
                                        PIN_OD_LOW(GPIOH_PIN15))

#define VAL_GPIOH_AFRL                 (PIN_AFIO_AF(GPIOH_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN7, 0U))

#define VAL_GPIOH_AFRH                 (PIN_AFIO_AF(GPIOH_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */